### PR TITLE
feat(aws-kms-provider): support signTypedMessage

### PR DESCRIPTION
**Pull request by ansoncsh**
Add the method signTypedMessage to support EIP-712

### CODE REVIEW

**Comment by odanado** [comment]
@ansoncsh 
Sorry for the late reply.

I am currently implementing a test for signTypedMessage

It would be easier to implement the tests if you have sample code using signTypedMessage. Do you have sample code?

**Comment by ansoncsh** [comment]
@odanado 

Sorry for my late response. Please find the sample code below:

```
const provider = new KmsProvider(rpcUrl, { region, keyIds: [keyId] });
const accounts = await provider.getAccounts();
const digest = "0xbe609aee343fb3c4b28e1df9e632fca64fcfaede20f02e86244efddf30957bd2"
const signature = await provider.signTypedMessage({
    from: accounts[0],
    data: digest
})
```

The parameter `digest` refers to [this EIP-712 example](https://github.com/ethereum/EIPs/blob/da0b41161071172aab07c73fafce58f1fdf1346d/assets/eip-712/Example.js)

**Comment by odanado** [comment]
@ansoncsh 
According to EIP-712, the second argument of eth_signTypedData should be the data before hashing
https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc

Have you tried implementing passing hashed data to data in other wallets such as MetaMask?

**Comment by ansoncsh** [comment]
> @ansoncsh According to EIP-712, the second argument of eth_signTypedData should be the data before hashing https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc
> 
> Have you tried implementing passing hashed data to data in other wallets such as MetaMask?

@odanado  I didn't try it

From my case,
- use KMS wallet to sign a meta transaction for Contract A
- pass signature to Contract B
- execute meta transaction from Contract B

Just notice that it works on my case but not work on MetaMask.

**Comment by odanado** [comment]
OK.

I tried signTypedMessage with ethers.
https://github.com/odan-sandbox/sign-typed-data-sandbox/blob/34add5f0f8411daf673ea360be1ca3ffcfd2f373/hooks/useSignTypedData.ts#L42-L47


This resulted in the following error.

```
Error: Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: {"types":{"Person":[{"name":"name","type":"string"},{"name":"wallet","type":"address"}],"Mail":[{"name":"from","type":"Person"},{"name":"to","type":"Person"},{"name":"contents","type":"string"}],"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}]},"domain":{"name":"Ether Mail","version":"1","chainId":"1","verifyingContract":"0xcccccccccccccccccccccccccccccccccccccccc"},"primaryType":"Mail","message":{"from":{"name":"Cow","wallet":"0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826"},"to":{"name":"Bob","wallet":"0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"},"contents":"Hello, Bob!"}}
```


I am implementing a fix to prevent this error from occurring.

**Comment by odanado** [comment]
@ansoncsh 
Changed eth_signTypedData to pass raw data as the second argument
Can you confirm that this is available for your use case?

**Comment by ansoncsh** [comment]
> @ansoncsh Changed eth_signTypedData to pass raw data as the second argument Can you confirm that this is available for your use case?

Yes, it works for my case too.
Thanks!

**Comment by odanado** [comment]
@ansoncsh LGTM
Thank you!

**Comment by odanado** [comment]
This change was released at `aws-kms-provider@0.9.0`.

**Pull request merged**
